version: 1.0.{build}
configuration: Release
platform: Any CPU
install:
  - choco install nsis
  - appveyor DownloadFile http://nsis.sourceforge.net/mediawiki/images/1/18/NsProcess.zip
  - 7z e -o"C:\Program Files (x86)\NSIS\Include" NsProcess.zip Include\*.nsh
  - 7z e -o"C:\Program Files (x86)\NSIS\Plugins\x86-ansi" NsProcess.zip Plugin\*.dll
  - set PATH="C:\Program Files (x86)\NSIS";%PATH%
before_build:
  - nuget restore
after_build:
  - Installer\MakeInstallers.bat
artifacts:
  - path: Installer\Target\*.exe
build:
  project: WTManager.sln
  parallel: true
  verbosity: minimal